### ISSUE TITLE
Connection to Gateway hotspot is lost while scanning Wi-Fi networks or trying to connect to one

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#304]
![image](https://user-images.githubusercontent.com/1311912/130392983-b298a16b-7fa5-4ea7-a6e6-d794ccab2dcc.png)

**Comment by hakunti** [comment]
![image](https://user-images.githubusercontent.com/25771106/130415815-9a2cf0aa-b630-4589-b78d-680d22c10fb4.png)

**Comment by ojousima** [comment]
This was probably related to #303 and fixed in c18e1e1.  Closing for now

**Comment by TheSomeMan** [comment]
@ojousima, @hakunti faced with another type of the problem which causes "Guru meditation error", now I'm trying to find the cause

**Comment by hakunti** [comment]
With the latest built I was not able to have anymore same issues. There are small glitches with the next button but it's maybe loading the next page.

**Comment by TheSomeMan** [comment]
yes, it was fixed in https://github.com/ruuvi/esp32-wifi-manager/issues/112

**Comment by laurijamsa** [comment]
Still getting this on the build 345 when trying to connect to a Wi-Fi network.

![image](https://user-images.githubusercontent.com/1311912/130601480-5d7aa4c1-7f19-4423-b031-db3f05751d1b.png)

Log:

``` 

(22705) wifi_manager: [sys_evt] ../components/esp32-wifi-manager/src/wifi_manager.c:524 {wifi_manager_event_handler}: WE
D (22707) wifi_manager: [wifi_manager] ../components/esp32-wifi-manager/src/wifi_manager.c:626 {wifi_handle_ev_scan_done}E
I (22721) http_server: [http_server] ap.json: [{"ssid":"Secret Network 2G","chan":9,"rssi":-59,"auth":3},
{"ssid":"AndroidAP22BE","chan":6,"rssi":-90,"auth":3}
]

I (22735) http_server: [http_server] Json resp: code=200, content:
[{"ssid":"Secret Network 2G","chan":9,"rssi":-59,"auth":3},
{"ssid":"AndroidAP22BE","chan":6,"rssi":-90,"auth":3}
]

I (22838) http_server: [http_server] Request from 10.10.0.2 to 10.10.0.1: GET /status.json
I (22839) http_server: [http_server] GET /status.json
I (22842) http_server: [http_server] status.json: {}

I (22848) http_server: [http_server] Json resp: code=200, content:
{}

I (22925) ruuvi_gateway: [main] free heap: 125500
I (23175) http_server: [http_server] Request from 10.10.0.2 to 10.10.0.1: POST /ruuvi.json
I (23176) http_server: [http_server] POST /ruuvi.json
D (23180) http_server: [http_server] ../main/json_ruuvi.c:122 {json_ruuvi_parse}: Got SETTINGS:
D (23188) http_server: [http_server] ../main/json_ruuvi.c:127 {json_ruuvi_parse}: use_eth: 0
I (23197) gw_cfg: [http_server] Gateway SETTINGS:
I (23202) gw_cfg: [http_server] config: use eth: 0
I (23207) gw_cfg: [http_server] config: use eth dhcp: 1
I (23213) gw_cfg: [http_server] config: eth static ip: 
I (23219) gw_cfg: [http_server] config: eth netmask: 
I (23225) gw_cfg: [http_server] config: eth gw: 
I (23230) gw_cfg: [http_server] config: eth dns1: 
I (23236) gw_cfg: [http_server] config: eth dns2: 
I (23241) gw_cfg: [http_server] config: use mqtt: 0
I (23247) gw_cfg: [http_server] config: mqtt server: 
I (23252) gw_cfg: [http_server] config: mqtt port: 0
I (23258) gw_cfg: [http_server] config: mqtt prefix: 
I (23264) gw_cfg: [http_server] config: mqtt client id: 
I (23270) gw_cfg: [http_server] config: mqtt user: 
I (23275) gw_cfg: [http_server] config: mqtt password: ********
I (23282) gw_cfg: [http_server] config: use http: 1
I (23288) gw_cfg: [http_server] config: http url: https://network.ruuvi.com/record
I (23296) gw_cfg: [http_server] config: http user: 
I (23301) gw_cfg: [http_server] config: http pass: ********
I (23308) gw_cfg: [http_server] config: LAN auth type: lan_auth_deny
I (23315) gw_cfg: [http_server] config: LAN auth user: 
I (23321) gw_cfg: [http_server] config: LAN auth pass: ********
I (23327) gw_cfg: [http_server] config: Auto update cycle: regular
I (23334) gw_cfg: [http_server] config: Auto update weekdays_bitmask: 0x7f
I (23342) gw_cfg: [http_server] config: Auto update interval: 00:00..24:00
I (23349) gw_cfg: [http_server] config: Auto update TZ: UTC+3
I (23356) gw_cfg: [http_server] config: coordinates: 
I (23361) gw_cfg: [http_server] config: use company id filter: 1
I (23368) gw_cfg: [http_server] config: company id: 0x0499
I (23374) gw_cfg: [http_server] config: use scan coded phy: 0
I (23381) gw_cfg: [http_server] config: use scan 1mbit/phy: 1
I (23387) gw_cfg: [http_server] config: use scan extended payload: 1
I (23394) gw_cfg: [http_server] config: use scan channel 37: 1
I (23400) gw_cfg: [http_server] config: use scan channel 38: 1
I (23407) gw_cfg: [http_server] config: use scan channel 39: 1
I (23413) ADV_POST_TASK: [http_server] adv_post_disable_retransmission
I (23422) ruuvi_gateway: [http_server] sending settings to NRF: use filter: 1, company id: 0x0499,use scan coded phy: 0,u1
I (23443) ETH: [http_server] Using ETH DHCP
I (23448) ETH: [http_server] ETH ip updated
I (23468) terminal_log: -----ACK-----

I (23468) terminal_log: CMD: RE_CA_UART_SET_ALL

I (23468) terminal_log: ACK state: RE_CA_ACK_OK

I (23550) http_server: [http_server] Request from 10.10.0.2 to 10.10.0.1: POST /connect.json
I (23551) http_server: [http_server] POST /connect.json
D (23555) http_server: [http_server] ../components/esp32-wifi-manager/src/http_server_handle_req.c:204 {http_server_handln
D (23572) http_server: [http_server] ../components/esp32-wifi-manager/src/http_server_handle_req.c:247 {http_server_handli
I (23592) http_server: [http_server] POST /connect.json: SSID:Secret Network 2G, PWD: ******** - connect to WiFi
D (23603) http_server: [http_server] ../components/esp32-wifi-manager/src/http_server_handle_req.c:253 {http_server_handll
I (23621) wifi_manager: [wifi_manager] MESSAGE: ORDER_CONNECT_STA
I (23631) http_server: [http_server] Json resp: code=200, content:
{}
I (23653) http_server: [http_server] Request from 10.10.0.2 to 10.10.0.1: GET /status.json
I (23654) http_server: [http_server] GET /status.json
I (23657) http_server: [http_server] status.json: {}

I (23663) http_server: [http_server] Json resp: code=200, content:
{}

I (25343) wifi:switch to channel 9
I (25344) wifi:ap channel adjust o:1,0 n:9,0
I (25344) wifi:new:<9,0>, old:<1,0>, ap:<9,0>, sta:<0,0>, prof:1
I (25346) wifi:new:<9,0>, old:<9,0>, ap:<9,0>, sta:<9,0>, prof:1
I (26005) wifi:state: init -> auth (b0)
I (27006) wifi:state: auth -> init (200)
I (27007) wifi:new:<9,0>, old:<9,0>, ap:<9,0>, sta:<9,0>, prof:1
I (27008) wifi_manager: [sys_evt] WIFI_EVENT_STA_DISCONNECTED
I (27013) wifi_manager: [wifi_manager] MESSAGE: EVENT_STA_DISCONNECTED with Reason code: 2
I (27021) wifi_manager: [wifi_manager] event_bits & WIFI_MANAGER_REQUEST_STA_CONNECT_BIT
I (27030) wifi_manager: [wifi_manager] Set STA IP String to: 0.0.0.0
I (32925) ruuvi_gateway: [main] free heap: 124532
I (42925) ruuvi_gateway: [main] free heap: 125680
I (52925) ruuvi_gateway: [main] free heap: 126372
I (62925) ruuvi_gateway: [main] free heap: 126372
I (72925) ruuvi_gateway: [main] free heap: 126372
I (80262) wifi:station: 50:ed:3c:37:14:85 leave, AID = 1, bss_flags is 134259, bss:0x3ffdf424
I (80263) wifi:new:<9,0>, old:<9,0>, ap:<9,0>, sta:<9,0>, prof:1
I (80266) wifi_manager: [sys_evt] WIFI_EVENT_AP_STADISCONNECTED
I (80272) wifi_manager: [wifi_manager] MESSAGE: EVENT_AP_STA_DISCONNECTED
I (80279) ruuvi_gateway: [wifi_manager] callback: on_ap_sta_disconnected
I (80287) ETH: [wifi_manager] Ethernet start
W (80292) esp_eth: driver started already
E (80296) ETH: [wifi_manager] ../main/ethernet.c:356 {ethernet_start}: Ethernet start failed, err=259 (ESP_ERR_INVALID_ST)
I (80308) ETH: [wifi_manager] Set hostname for Ethernet interface: RuuviGatewayD4E2
I (80317) reset_task: [wifi_manager] Start AP timer for 60 seconds
I (80324) ADV_POST_TASK: [wifi_manager] adv_post_enable_retransmission
I (80331) dns_server: [wifi_manager] Send request to stop DNS-Server
I (81037) dns_server: [dns_server] Got signal STOP
I (81037) dns_server: [dns_server] Stop DNS Server
 ```

**Comment by TheSomeMan** [comment]
That's different kind of the problem and it can't be fixed. I'm not sure if it's hardware problem or esp-idf system library problem.
Connection between PC and hotspot can be lost while ESP32 scans for WiFi networks. Sometimes PC automatically reconnects to the hotspot, sometimes it connects to previous WiFi or just lost connection. In this case the overlay-page is displayed: "The connection to the Ruuvi Gateway is lost".
Such problem can occur only on "Internet Connection" or "WiFi network" pages when requests for "ap.json" are performed.
P.S. the problem that was fixed is "Guru Meditaion Error" which causes the gateway reboot and connection lost.

**Comment by laurijamsa** [comment]
I'm still getting this connection lost error all the time when scanning wi-fi networks. I noticed this from the logs:

``` 
I (811165) http_server: [http_server] Json resp: code=200, content:
[{"ssid":"Weak Signal","chan":9,"rssi":-37,"auth":3},
{"ssid":"Secret Network 2G","chan":9,"rssi":-66,"auth":3},
{"ssid":"AndroidAP22BE","chan":6,"rssi":-93,"auth":3}
]

E (812691) http_server: [http_server] ../components/esp32-wifi-manager/src/http_server.c:926 {http_server_recv_and_handle)
W (812695) http_server: [http_server] The connection was closed by the client side
``` 

Note the last line which is not true.

**Comment by TheSomeMan** [comment]
The phrase "The connection was closed by the client side" is not quite correct. I meant that the connection closed by the other side, but not by the gateway. The connection between PC and gateway was broken for some reason, previous line should print the error code, but I don't see it in your log. It should be like "netconn recv: 1001 (time: 1000 ticks)"

**Comment by hakunti** [comment]
I had yesterday problems with bad USB cable or too less power from computer. After changing power source it didn't restart. Now testing latest firmware.

**Comment by laurijamsa** [comment]
This time I fully erased memory of 2 Gateways and flashed build 364. Now I experience definitely less problems than before but still getting this message sometimes but I cannot reproduce it every time. Afaik erasing the flash shouldn't affect because those issues were fixed earlier, but this time it did have some effect.

**Comment by laurijamsa** [comment]
I fixed name of the issue. Hopefully this will be fixed completely when we will update the ESP-IDF. Moving to backlog.

**Comment by TheSomeMan** [comment]
It seems that the problem is in Wi-Fi driver, it should scan for Wi-Fi AP in the background mode to give time for the currently used channel.
![image](https://user-images.githubusercontent.com/4346875/131351867-4cf34b16-33d5-47e8-a780-00c1ac321da9.png)

![image](https://user-images.githubusercontent.com/4346875/131351941-15c244dd-be5c-4a0a-b6a3-e84ea279c1c0.png)

But it looks like that 30ms is not enough or WiFi driver is not switched to the current channel at all and works in foreground mode.

**Comment by laurijamsa** [comment]
I am still having these exactly same issues with the build 378. I tried with 4 different Gateway units and all are not working well. Tried with 2 different Wi-Fi networks and 3 different configuration devices. Used a wall USB power adapter.

I guess we need to wait for more user feedback.

**Comment by TheSomeMan** [comment]
@laurijamsa could you please attach your logs for the latest build?

**Comment by laurijamsa** [comment]
Here are 2 logs with 2 different Gateway units. I used Samsung Galaxy S21 Ultra's tethering as a Wi-Fi network and MacBook Air with M1 chip (same machine I recorded the log with) to configure.

[mokkilogi-build378-first-hw.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/7110312/mokkilogi-build378-first-hw.txt)
[mokkilogi-build378-second-hw.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/7110313/mokkilogi-build378-second-hw.txt)

**Comment by laurijamsa** [comment]
And this is when trying to configure using an old Lenovo Android tablet. Same error.

[mokkilogi-build378-first-hw-tabletconfigure.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/7110323/mokkilogi-build378-first-hw-tabletconfigure.txt)

**Comment by laurijamsa** [comment]
We got a user report about this issue. Currently, I have no more information than this screenshot:

![image](https://user-images.githubusercontent.com/1311912/132993225-0fc19da5-ad38-419d-b9db-2b9968e83b3a.png)

**Comment by laurijamsa** [comment]
Another report from a user with a log (1.8.2 firmware):

[Gateway_Error_Connection_lost.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/7315518/Gateway_Error_Connection_lost.txt)

**Comment by markoaamunkajo** [comment]
Not seen anymore

**Comment by laurijamsa** [comment]
Reopening this one because got this again when tried to configure Wi-Fi on the latest dirty firmware v1.12.1-8-g4f1c8f8-dirty.

Log:

```
I (282923) ADV_POST_TASK: [adv_post_task] Got ADV_POST_SIG_RETRANSMIT
W (282923) ADV_POST_TASK: [adv_post_task] Can't send advs, no network connection
W (282927) ADV_POST_TASK: [adv_post_task] Can't send statistics, no network connection
W (284191) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (285481) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (286763) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
I (287722) ruuvi_gateway: [main] free heap: 122960
W (288051) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (289330) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (290622) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
I (290780) wifi:station: 50:ed:3c:37:14:85 leave, AID = 1, bss_flags is 134259, bss:0x3ffdf8c0
I (290781) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<0,0>, prof:1
I (290784) wifi_manager: [sys_evt] WIFI_EVENT_AP_STADISCONNECTED
I (290790) wifi_manager: [wifi_manager] MESSAGE: EVENT_AP_STA_DISCONNECTED
I (290798) wifi_manager: [wifi_manager] WIFI_MANAGER:EV_STATE: Clear WIFI_MANAGER_AP_STA_CONNECTED_BIT | WIFI_MANAGER_AP_STA_IP_ASSIGNED_BIT
I (290811) ruuvi_gateway: [wifi_manager] callback: on_ap_sta_disconnected
I (290818) ETH: [wifi_manager] Ethernet start
W (290823) esp_eth: driver started already
E (290828) ETH: [wifi_manager] ../main/ethernet.c:389 {ethernet_start}: Ethernet start failed, err=259 (ESP_ERR_INVALID_STATE)
I (290840) ETH: [wifi_manager] Set hostname for Ethernet interface: RuuviGatewayB318
I (290849) ruuvi_gateway: [wifi_manager] Start AP timer for 60 seconds
I (290856) ADV_POST_TASK: [wifi_manager] adv_post_enable_retransmission
I (290863) dns_server: [wifi_manager] Send request to stop DNS-Server
I (291308) dns_server: [dns_server] Got signal STOP
I (291308) dns_server: [dns_server] Stop DNS Server
I (291308) dns_server: [dns_server] TaskWatchdog: Unregister current thread
I (291316) dns_server: [dns_server] TaskWatchdog: Stop timer
I (291322) dns_server: [dns_server] TaskWatchdog: Delete timer
I (291328) dns_server: [dns_server] Close socket
W (291898) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
I (292923) ADV_POST_TASK: [adv_post_task] Got ADV_POST_SIG_RETRANSMIT
W (292923) ADV_POST_TASK: [adv_post_task] Can't send advs, no network connection
W (292927) ADV_POST_TASK: [adv_post_task] Can't send statistics, no network connection
W (293184) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (294471) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (295764) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (297038) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
I (297722) ruuvi_gateway: [main] free heap: 127816
W (298327) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (300907) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (302181) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
I (302923) ADV_POST_TASK: [adv_post_task] Got ADV_POST_SIG_RETRANSMIT
W (302923) ADV_POST_TASK: [adv_post_task] Can't send advs, no network connection
W (302927) ADV_POST_TASK: [adv_post_task] Can't send statistics, no network connection
W (303474) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (304755) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (306040) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (307318) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
I (307722) ruuvi_gateway: [main] free heap: 128024
W (308612) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (309895) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (311181) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
W (312462) ADV_POST_TASK: [rx_parse_task] Drop adv - no network connection
I (312923) ADV_POST_TASK: [adv_post_task] Got ADV_POST_SIG_RETRANSMIT
W (312923) ADV_POST_TASK: [adv_post_task] Can't send advs, no network connection
W (312927) ADV_POST_TASK: [adv_post_task] Can't send statistics, no network connection
```

<img width="965" alt="image" src="https://user-images.githubusercontent.com/1311912/175944696-0f6cac70-0957-48b4-8596-702691b0c9dc.png">

**Comment by ojousima** [comment]
Not seeing this with `v1.12.1-36-g1091112` @laurijamsa can you retry?

**Comment by TheSomeMan** [comment]
Perhaps, this relates to #601, #603

**Comment by laurijamsa** [comment]
Couldn't reproduce today with the build 684.

**Comment by laurijamsa** [comment]
I got this same error again on the build 708 when Gateway tried to connect to my Wi-Fi network:

```
I (170838) http_server: [http_server/4] Response: OK
I (171214) http_server: [http_server/4] Request from 10.10.0.2 to 10.10.0.1 (Host: 10.10.0.1): POST /ruuvi.json
I (171217) http_server: [http_server/4] POST /ruuvi.json
I (171222) gw_cfg: [http_server/4] Gateway SETTINGS (via HTTP):
I (171227) gw_cfg: [http_server/4] config: Use eth: no
I (171233) gw_cfg: [http_server/4] config: eth: use DHCP: yes
I (171239) gw_cfg: [http_server/4] config: eth: static IP: 
I (171246) gw_cfg: [http_server/4] config: eth: netmask: 
I (171252) gw_cfg: [http_server/4] config: eth: GW: 
I (171257) gw_cfg: [http_server/4] config: eth: DNS1: 
I (171263) gw_cfg: [http_server/4] config: eth: DNS2: 
W (171269) gw_cfg: [http_server/4] Can't find key 'wifi_ap_config/password' in config-json
I (171278) gw_cfg: [http_server/4] config: wifi_ap_config: SSID: RuuviGatewayC526
I (171286) gw_cfg: [http_server/4] config: wifi_ap_config: password: 
I (171293) gw_cfg: [http_server/4] config: wifi_ap_config: ssid_len: 0
I (171301) gw_cfg: [http_server/4] config: wifi_ap_config: channel: 9
I (171308) gw_cfg: [http_server/4] config: wifi_ap_config: auth_mode: OPEN
I (171315) gw_cfg: [http_server/4] config: wifi_ap_config: ssid_hidden: 0
I (171323) gw_cfg: [http_server/4] config: wifi_ap_config: max_connections: 4
I (171330) gw_cfg: [http_server/4] config: wifi_ap_config: beacon_interval: 100
I (171338) gw_cfg: [http_server/4] config: wifi_ap_settings: bandwidth: 20MHz
I (171346) gw_cfg: [http_server/4] config: wifi_ap_settings: IP: 10.10.0.1
I (171354) gw_cfg: [http_server/4] config: wifi_ap_settings: GW: 10.10.0.1
I (171361) gw_cfg: [http_server/4] config: wifi_ap_settings: Netmask: 255.255.255.0
I (171370) ruuvi_gateway: [http_server/4] ruuvi_cb_on_change_cfg: settings_save_to_flash
E (171384) settings: [http_server/4] ../main/settings.c:63 {settings_read_gw_cfg_json_from_nvs}: Can't find config key 'ruuvi_cfg_json' in flash, err=4354 (ESP_ERR_NVS_)
W (171395) settings: [http_server/4] settings_read_gw_cfg_json_from_nvs failed
I (171409) settings: [http_server/4] ### Save config to NVS: successfully updated
I (171411) ruuvi_gateway: [http_server/4] ruuvi_cb_on_change_cfg: http_server_set_auth: lan_auth_default
I (171422) ruuvi_gateway: [http_server/4] ruuvi_cb_on_change_cfg: settings_save_to_flash
I (171443) settings: [http_server/4] ### Save config to NVS: successfully updated
I (171443) ruuvi_gateway: [http_server/4] ruuvi_cb_on_change_cfg: http_server_set_auth: lan_auth_default
I (171451) ADV_POST_TASK: [http_server/4] adv_post_disable_retransmission
I (171458) http_server: [http_server/4] Response: OK
I (171467) ADV_POST_TASK: [adv_post_task/1] Got ADV_POST_SIG_GW_CFG_READY
I (171471) ruuvi_gateway: [adv_post_task/1] ### sending settings to NRF: use filter: 1, company id: 0x0499,use scan coded phy: 0,use scan 1mbit/phy: 1,use scan extended1
I (171494) ADV_POST_TASK: [adv_post_task/1] Start timer for advs retransmission
I (171502) ADV_POST_TASK: [adv_post_task/1] Start timer to send statistics
I (171554) http_server: [http_server/4] Request from 10.10.0.2 to 10.10.0.1 (Host: 10.10.0.1): POST /connect.json
I (171555) http_server: [http_server/4] POST /connect.json
I (171561) http_server: [http_server/4] http_server_netconn_serve: POST /connect.json
I (171572) http_server: [http_server/4] POST /connect.json: SSID:Secret Network 2G, PWD: ******** - connect to WiFi
I (171581) wifi_manager: [http_server/4] wifi_manager_connect_async: wifiman_msg_send_cmd_connect_sta: CONNECTION_REQUEST_USER
I (171592) wifi_manager: [http_server/4] Send msg: ORDER_CONNECT_STA, conn_req_code=1
I (171601) wifi_manager: [wifi_manager/5] MESSAGE: ORDER_CONNECT_STA: CONNECTION_REQUEST_USER, event_bits=0x041d
I (171612) wifi_manager: [wifi_manager/5] WIFI_MANAGER:EV_STATE: Set WIFI_MANAGER_REQUEST_STA_CONNECT_BIT
I (171622) wifi_manager: [wifi_manager/5] WIFI_MANAGER:EV_STATE: Clear WIFI_MANAGER_REQUEST_DISCONNECT_BIT
I (171634) http_server: [http_server/4] Json resp: code=200, content:
{}
I (171640) http_server: [http_server/4] Response: OK
I (171676) http_server: [http_server/4] Request from 10.10.0.2 to 10.10.0.1 (Host: 10.10.0.1): GET /status.json
I (171678) http_server: [http_server/4] Json resp: code=200, content:
{}

I (171684) http_server: [http_server/4] Response: OK
I (172741) http_server: [http_server/4] Request from 10.10.0.2 to 10.10.0.1 (Host: 10.10.0.1): GET /status.json
I (172744) http_server: [http_server/4] Json resp: code=200, content:
{}

I (172751) http_server: [http_server/4] Response: OK
I (173127) wifi:switch to channel 9
I (173128) wifi:ap channel adjust o:1,0 n:9,0
I (173128) wifi:new:<9,0>, old:<1,0>, ap:<9,0>, sta:<0,0>, prof:1
I (173131) wifi:new:<9,0>, old:<9,0>, ap:<9,0>, sta:<9,0>, prof:1
I (174012) wifi:state: init -> auth (b0)
I (175014) wifi:state: auth -> init (200)
I (175015) wifi:new:<9,0>, old:<9,0>, ap:<9,0>, sta:<9,0>, prof:1
I (175016) wifi_manager: [sys_evt/20] WIFI_EVENT_STA_DISCONNECTED, reason=2 (AUTH_EXPIRE)
I (175023) wifi_manager: [wifi_manager/5] MESSAGE: EVENT_STA_DISCONNECTED with Reason code: 2 (AUTH_EXPIRE), event_bits=0x043d
I (175034) wifi_manager: [wifi_manager/5] A user-initiated connection to WiFi AP has failed (maybe because of wrong password)
I (175046) wifi_manager: [wifi_manager/5] WIFI_MANAGER:EV_STATE: Clear WIFI_MANAGER_REQUEST_STA_CONNECT_BIT
I (175057) wifi_manager: [wifi_manager/5] Set STA IP String to: 0.0.0.0
I (175063) wifi_manager: [wifi_manager/5] WIFI_MANAGER:EV_STATE: Clear WIFI_MANAGER_WIFI_CONNECTED_BIT | WIFI_MANAGER_ETH_CONNECTED_BIT
E (175259) http_server: [http_server/4] ../components/esp32-wifi-manager/src/http_server_accept_and_handle_conn.c:161 {http_server_netconn_write}: netconn_write_partly )
E (175266) http_server: [http_server/4] ../components/esp32-wifi-manager/src/http_server_accept_and_handle_conn.c:194 {http_server_netconn_printf}: http_server_netconn_d
E (175283) http_server: [http_server/4] ../components/esp32-wifi-manager/src/http_server_accept_and_handle_conn.c:412 {http_server_netconn_resp_with_content}: http_servd
I (177784) ruuvi_gateway: [main/1] free heap: 120016
W (181029) ADV_POST_TASK: [rx_parse_task/1] Drop adv - no network connection
I (181502) ADV_POST_TASK: [adv_post_task/1] Got ADV_POST_SIG_RETRANSMIT
I (187784) ruuvi_gateway: [main/1] free heap: 120884
I (191502) ADV_POST_TASK: [adv_post_task/1] Got ADV_POST_SIG_RETRANSMIT
I (197784) ruuvi_gateway: [main/1] free heap: 113660
```

**Comment by TheSomeMan** [comment]
As I see now you have regular error:
```
I (175016) wifi_manager: [sys_evt/20] WIFI_EVENT_STA_DISCONNECTED, reason=2 (AUTH_EXPIRE)
```

**Comment by laurijamsa** [comment]
Full log: 
[708-after-erase-and-flash.log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9459002/708-after-erase-and-flash.log)

**Comment by laurijamsa** [comment]
After this latest failed configuration attempt, I noticed suddenly after a few minutes that the green led was on. I opened terminal and recorded this log:

[708-green-light-is-on.log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9459339/708-green-light-is-on.log)

**Comment by laurijamsa** [comment]
A new test. Erased flash, flashed build 708, powered on, connected to hotspot, tried to connect to my wi-fi, loading icon was visible ~15 sec, then got this familiar error:

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/1311912/187632302-6b53c93d-a04a-4e8a-b095-27de39418553.png">

Full log:
[708-erase-flash.log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9459915/708-erase-flash.log)

**Comment by laurijamsa** [comment]
Now I tried to erase flash, flash 708, join hotspot using iPhone SE, join wi-fi -> crash:

![telegram-cloud-photo-size-5-6087081871461693101-y](https://user-images.githubusercontent.com/1311912/187638506-f48b3a7f-8277-4535-888e-67fb3fc6c676.jpg)

Full log:
[708-erase-flash-configure-using-iphone-se-crashed-when-joining-wifi.log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9460073/708-erase-flash-configure-using-iphone-se-crashed-when-joining-wifi.log)

**Comment by TheSomeMan** [comment]
> Now I tried to configure the gateway using my mobile phone. I didn't get the same "connection lost" message but the connection got lost anyways. Full log here: [708-after-erase-and-flash-configured-using-samsung-galaxy-s21.log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9459278/708-after-erase-and-flash-configured-using-samsung-galaxy-s21.log)

The problem is that the gateway couldn't deliver the response to the browser:
```
I (171310) http_server: [http_server/4] Response: OK
E (173818) http_server: [http_server/4] ../components/esp32-wifi-manager/src/http_server_accept_and_handle_conn.c:161 {http_server_netconn_write}: netconn_write_partly failed: send timeout (2500 ms)
E (173825) http_server: [http_server/4] ../components/esp32-wifi-manager/src/http_server_accept_and_handle_conn.c:194 {http_server_netconn_printf}: http_server_netconn_write failed
E (173842) http_server: [http_server/4] ../components/esp32-wifi-manager/src/http_server_accept_and_handle_conn.c:412 {http_server_netconn_resp_with_content}: http_server_netconn_printf failed
```

Later, you saw green LED because Wi-Fi connection with the gateway was lost, so hospot was stopped and the previous configuration was used.
It looks like you have many Wi-Fi networks nearby, and they often conflict.

**Comment by TheSomeMan** [comment]
> Full log:
> [708-erase-flash-configure-using-iphone-se-crashed-when-joining-wifi.log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9460073/708-erase-flash-configure-using-iphone-se-crashed-when-joining-wifi.log)

```
I (406218) wifi_manager: [sys_evt/20] WIFI_EVENT_STA_DISCONNECTED, reason=2 (AUTH_EXPIRE)
```

**Comment by laurijamsa** [comment]
Another try. On this log you can see ethernet test first and then two wrong password wi-fi joining tests, and finally using the correct password. Now the captive browser closed on the iphone se without even showing the error message first:

[708-erase-flash-configure-using-iphone-se-crashed-when-joining-wifi-by-dropping-out.log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9460167/708-erase-flash-configure-using-iphone-se-crashed-when-joining-wifi-by-dropping-out.log)

**Comment by laurijamsa** [comment]
> It looks like you have many Wi-Fi networks nearby, and they often conflict.

No. Only one (2,4GHz and 5GHz versions of it).

**Comment by ojousima** [comment]
Check if this is still an issue
